### ISSUE TITLE
Feature request: Test libsecp256k1 as part of the cryptofuzz effort

### ISSUE THREAD

**Issue by practicalswift** [guidovranken/cryptofuzz#13]
Thanks for a great project! Really interesting to follow.

It would be awesome to have [`libsecp256k1`](https://github.com/bitcoin-core/secp256k1) tested as part of the cryptofuzz effort.

**Comment by guidovranken** [comment]
Working on this: https://github.com/guidovranken/cryptofuzz/tree/ecdsa/modules/secp256k1

**Comment by practicalswift** [comment]
@guidovranken Wow! That's excellent news! Let me know if you need testing or any other help! :)

**Comment by MarcoFalke** [comment]
Can be closed?

**Comment by guidovranken** [comment]
Yes.
