### ISSUE TITLE
[RFC] update the TODO document

### ISSUE THREAD

**Issue by pcy190** [guidovranken/cryptofuzz#16]
I notice that the `TODO.md` haven't been updated since 1 Sep 2019.

Many of modules mentions in `todo.md` has been implemented already.   
So we might need to update it, delete the finish module,  and add some new modules perhaps.

**Comment by guidovranken** [comment]
Thank you for your suggestion. I've been keeping a todo list in a document offline. Maybe I'll migrate that to the project wiki in the future. I've now deleted `TODO.md` to avoid confusion.
