### ISSUE TITLE
an issue building latest cryptofuzz + botan

### ISSUE THREAD

**Issue by busterb** [guidovranken/cryptofuzz#48]
Noticed in LibreSSL Fuzzing tests that the build broke recently:

https://github.com/libressl-portable/portable/actions/runs/3728363628/jobs/6328445872#step:4:24696

**Comment by randombit** [comment]
In botan master we recently decided to start using C++20 instead of C++17, so compile flags would need to be adjusted here

**Comment by armfazh** [comment]
Similar building issues observed in CIRCL fuzzing job.

**Comment by armfazh** [comment]
In https://github.com/guidovranken/cryptofuzz/commit/7687f247c2b3e121dbfcc284232c56cd9f3ef498 this was partially addressed, but still the `Makefile-oracle` needs to be updated.

https://github.com/guidovranken/cryptofuzz/blob/d6fce8710b7c6c9ca2399754a2ed13f3a1a5006c/modules/botan/Makefile-oracle#L3

**Comment by guidovranken** [comment]
Apologies, I forgot the update both the Makefiles, like @armfazh says. This is now fixed.

An additional issue with libressl and some other projects is that the libgmp.org certificate has expired. I'm addressing that in this PR: https://github.com/google/oss-fuzz/pull/9314
