### ISSUE TITLE
can't compile on macOS

### ISSUE THREAD

**Issue by maldiohead** [guidovranken/cryptofuzz#6]
this is throw error~
![image](https://user-images.githubusercontent.com/23315692/61182286-aadb9080-a663-11e9-8ef0-86d496d96d89.png)

**Comment by guidovranken** [comment]
You must first run ```gen_repository.py```.

**Comment by maldiohead** [comment]
ok,thank you!~

**Comment by guidovranken** [comment]
You're welcome.
