### ISSUE TITLE
Involvement in GitHub's TOP 5k project may qualify you for StarkNet airdrops, offering $200 to $20,000.

### ISSUE THREAD

**Issue by mando61** [guidovranken/cryptofuzz#68]
* StarkNet's Developer Airdrop Initiative
* The StarkNet project has launched an airdrop to foster developer interest in its development. Developers with PRs to GitHub projects with significant stars could qualify for an airdrop ranging from 111.1 to 13,911 STRK tokens, currently valued at about two dollars each. OAuth 2.0 is required for claiming.
* Airdrop Eligibility Details
* By the cutoff date of November 15, 2023, you should have contributed at least three times to any of the top 5,000 repositories globally, with at least one contribution in or after 2018.
    * Procedure to Claim Airdrop
    * Obtain your address from https://provisions.starknet.io/.
    * Visit the airdrop claim page, link your wallet (Argent X recommended), and sign in through GitHub with OAuth 2.0.
    * Accept your STRK airdrop directly, with little to no follow-up required.
    * Then, you may choose to exchange your STRK for USDT on a trading platform or hold onto them.
* Advice Following Receipt
* Given the increased scrutiny and restrictions by BN and OK, Bitget is suggested for STRK trades, available at https://partner.bitget.fit/bg/74T4P8. Make sure the receipt address is correct.
* If you need more information, you're welcome to reach out on Telegram (https://t.me/XiaoAnBtc) or Twitter (https://twitter.com/xiaoanbtc).
* For trading, consider platforms like Binance (for high-volume transactions, register here: https://accounts.binance.com/register?ref=LK3RXF2O), OKX (known for its excellent user experience, sign-up here: https://okx.com/join/6520854), and Bitget (a platform recognized for its innovation, with the same link as provided).

**Comment by guidovranken** [comment]
Blocked.
