### ISSUE TITLE
KDF_PBKDF2 tests libraries including unsupported operations

### ISSUE THREAD

**Issue by koharin** [guidovranken/cryptofuzz#73]
Hi.
I'm using cryptofuzz to test cryptographic libraries.

I recognized that when testing KDF_PBKDF2, it produces incorrect difference.
For example, KDF_PBKDF2 in libgmp, linux, mpdecimal, blst, libsodim, bearssl, trezor-firmware, openssl libraries don't support SHAKE digest.
However, cryptofuzz test KDF_PBKDF2 with SHAKE digest, so that it catches as result is not correct.

It would be better to filter out libraries with unsupported algorithms before testing algorithms.

Thank you for your works for Cryptofuzz.

**Comment by gilles-peskine-arm** [comment]
This is the same problem as https://github.com/guidovranken/cryptofuzz/issues/69. You need to return `std::nullopt` in your `Module` implementation when given an unsupported or invalid input.

**Comment by koharin** [comment]
I'll add `std::nullopt` in module for unsupported input. 
Thanks for your instruction.
