### ISSUE TITLE
Order of evaluation issues

### ISSUE THREAD

**Issue by dergoegge** [guidovranken/cryptofuzz#81]
In C++: [*Order of evaluation of any part of any expression, including order of evaluation of function arguments is unspecified*](https://en.cppreference.com/w/cpp/language/eval_order).

Cryptofuzz assumes a fixed order of evaluation which is fine when only using one compiler, but as soon as results are compared across compilers, differences will manifest due to different evaluation order choices of the used compilers.

For example, looking at the openssl module:
https://github.com/guidovranken/cryptofuzz/blob/292701cc5e0aa0ae61e4b41ee5bead024ebb218e/modules/openssl/module.cpp#L3452

`group`, `pub` and `prv` all own a reference to the same `Datasource` and consume from it when `GetPtr` is called, but the order in which `GetPtr` will be called on each of the three is up to the compiler. Given the same fuzz input, this leads to a different `EC_POINT_mul` result between e.g. gcc and clang.

I'm not sure what the best approach would be to find and fix all instances of this (there were some suggestion on a Bitcoin Core PR (https://github.com/bitcoin/bitcoin/pull/29043) dealing with the same issue: using [-Wsequence-point](https://github.com/bitcoin/bitcoin/pull/29043#issuecomment-1867538883) or a [clang-tidy query](https://github.com/bitcoin/bitcoin/pull/29043#pullrequestreview-1820019492), but they all have their limits).

So far, I've only observed this in the openssl module for `OpECC_Point_Mul` and `OpECC_PrivateToPublic` but I could see how there are others (probably most of the *ssl modules, they seem to have very similar code).

I'm happy to send patches for any occurrences I come across but a more comprehensive approach would obviously be some kind of linter to find all current and future occurrences.

**Comment by guidovranken** [comment]
Thank you for raising this issue. The code base is filled with instances of this. I asked an LLM and it came up with a few solutions:

- Use std::invoke (C++17 and later):
   ```cpp
   fn(std::invoke(a), std::invoke(b), std::invoke(c));
   ```
   This ensures that a(), b(), and c() are called in the order they appear.

- Create a wrapper function:
   ```cpp
   template<typename Func, typename... Args>
   auto call_in_order(Func f, Args... args) {
       return f((args())...);
   }

   // Usage
   call_in_order(fn, a, b, c);
   ```
   This wrapper ensures the arguments are evaluated in the order they're passed.

- Use immediately invoked lambdas:
   ```cpp
   fn([&]() {
       auto arg1 = a();
       auto arg2 = b();
       auto arg3 = c();
       return std::make_tuple(arg1, arg2, arg3);
   }());
   ```
   This requires modifying the function to accept a tuple of arguments.

- If using C++20, use std::bind_front:
   ```cpp
   auto bound_fn = std::bind_front(fn, a(), b(), c());
   bound_fn();
   ```
   This evaluates the arguments in order when binding, before calling the function.

Have you explored any of these?

**Comment by dergoegge** [comment]
All the approaches the LLM suggested don't actually work, except for "immediately invoked lambdas" (see https://godbolt.org/z/9K5rYsahP). That approach works because it pulls the function calls out into individual assignments.

I've drafted a [branch](https://github.com/dergoegge/cryptofuzz/commits/2024-07-cf-ordered-eval/) that introduces a macro `CF_ORDERED_EVAL` that avoids having to manually type out the individual assignments (see https://godbolt.org/z/3qrhGvvaG). With the macro, the refactoring that is needed should usually be contained to one line:

```c++
CF_CHECK_NE(EC_POINT_mul(group->GetPtr(), res->GetPtr(), nullptr, a->GetPtr(), b.GetPtr(), nullptr), 0);
// Using CF_ORDERED_EVAL this would turn into:
CF_CHECK_NE(std::apply(EC_POINT_mul, CF_ORDERED_EVAL(group->GetPtr(), res->GetPtr(), nullptr, a->GetPtr(), b.GetPtr(), nullptr)), 0);
```

What do you think of this approach?
